version: '3.4'

services:
  s_apigateway:
    container_name: c_apigateway
    image: sametduran/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    networks:
      - net_api
      - int_net_api
    ports:
      - 80:80

  s_contact_api:
    container_name: c_contact_api
    image: sametduran/contactapi
    build:
      context: .
      dockerfile: Services/ContactAPI/Contact.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9001:9001

  s_res_api:
    container_name: c_res_api
    image: sametduran/resapi
    build:
      context: .
      dockerfile: Services/ReservationAPI/Reservation.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 7001:7001


networks:
  net_api:
    driver: bridge

  int_net_api:
    driver: overlay
    internal: true